# Generated by Django 6.0 on 2026-06-17 05:13

import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Mercado',
                'verbose_name_plural': 'Mercados',
                'db_table': 'mercado',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('accion', models.TextField()),
                ('tipo_operacion', models.CharField(max_length=10)),
                ('datos_previos', models.JSONField(blank=True, db_column='datos_previos', null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'db_table': 'auditoria_log',
            },
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nemotecnico', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('inscrito', models.BooleanField(default=True)),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrumentos', to='tributacion.mercado')),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
                'db_table': 'instrumento',
            },
        ),
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.IntegerField()),
                ('fecha_pago', models.DateField()),
                ('secuencia', models.IntegerField()),
                ('nro_dividendo', models.IntegerField()),
                ('tipo_sociedad', models.CharField(max_length=1)),
                ('valor_historico', models.DecimalField(decimal_places=4, max_digits=18)),
                ('fuente_ingreso', models.CharField(max_length=50)),
                ('factor_8', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_9', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_10', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_11', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_12', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_13', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_14', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_15', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_16', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_17', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_18', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_19', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_20', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_21', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_22', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_23', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_24', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_25', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_26', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_27', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_28', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_29', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_30', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_31', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_32', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_33', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_34', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_35', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_36', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('factor_37', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=9)),
                ('monto_8', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('monto_9', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('monto_10', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('monto_11', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('monto_12', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('monto_13', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('monto_14', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('monto_15', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('monto_16', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('monto_17', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('monto_18', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('monto_19', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tributacion.instrumento')),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tributacion.mercado')),
            ],
            options={
                'verbose_name': 'Calificación Tributaria',
                'verbose_name_plural': 'Calificaciones Tributarias',
                'db_table': 'calificacion_tributaria',
                'constraints': [models.CheckConstraint(condition=models.Q(('secuencia__gt', 10000)), name='chk_secuencia_minima'), models.CheckConstraint(condition=models.Q(('tipo_sociedad__in', ['A', 'C'])), name='chk_tipo_sociedad'), models.CheckConstraint(condition=models.Q(('factor_8__lte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.Value(Decimal('1.00000000')), '-', models.F('factor_9')), '-', models.F('factor_10')), '-', models.F('factor_11')), '-', models.F('factor_12')), '-', models.F('factor_13')), '-', models.F('factor_14')), '-', models.F('factor_15')), '-', models.F('factor_16')), '-', models.F('factor_17')), '-', models.F('factor_18')), '-', models.F('factor_19')))), name='chk_suma_factores')],
                'unique_together': {('ejercicio', 'instrumento', 'secuencia')},
            },
        ),
    ]
