# Generated by Django 6.0 on 2026-06-30 00:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calificaciontributaria',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='corredor_propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_actualizacion',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=18),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='isfut',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='calificaciontributaria',
            unique_together={('ejercicio', 'instrumento', 'secuencia', 'corredor_propietario')},
        ),
    ]
